name: qrc-coherence
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.0.3
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.10.4
  - readline=8.1.2
  - setuptools=63.4.1
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.5
    - commonmark==0.9.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - fonttools==4.37.3
    - idna==3.4
    - kiwisolver==1.4.4
    - llvmlite==0.40.1
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - numba==0.57.1
    - numpy==1.23.3
    - pandas==1.5.0
    - pexpect==4.8.0
    - pillow==9.2.0
    - ptyprocess==0.7.0
    - pygments==2.13.0
    - pyparsing==3.0.9
    - qutip==4.7.0
    - scipy==1.9.1
    - seaborn==0.12.0
    - six==1.16.0
    - urllib3==1.26.12
